shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from store.views import main_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_view, name='base'),
    path('', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from store.views import (
    category_view,
    product_view,
    parent_category_view,
    cart_view,
    add_to_cart_view,
    remove_from_cart_view,
    change_item_quantity,
    checkout_view,
    make_order_view,
    account_view,
    logout_view)

urlpatterns = [
    path('category/<category_slug>/', category_view, name='category_detail'),
    path('product/<product_slug>/', product_view, name='product_detail'),
    path('<parent_category_slug>', parent_category_view, name='parent_category_detail'),
    path('add_to_cart/', add_to_cart_view, name='add_to_cart'),
    path('remove_from_cart/', remove_from_cart_view, name='remove_from_cart'),
    path('change_item_quantity/', change_item_quantity, name='change_item_quantity'),
    path('cart/', cart_view, name='cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('make_order/', make_order_view, name='make_order'),
    path('thank_you/', TemplateView.as_view(template_name='thank_you.html'), name='thank_you'),
    path('account/', account_view, name='account'),
    path('logout/', logout_view, name='logout')
]

store/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from transliterate import translit
from django.urls import reverse
from django.conf import settings

# Creating functions for models
def image_folder(instanse, fileName):
    fileName = instanse.slug + '.' + fileName.split('.')[1]
    return "{0}/{1}".format(instanse.slug, fileName)


# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class ParentCategory(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(blank=True)
    image = models.ImageField(upload_to= image_folder, blank=True, default=None)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('parent_category_detail', kwargs={'parent_category_slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(blank=True)
    parentCategory = models.ForeignKey(ParentCategory, on_delete=models.CASCADE, default=None, db_index=True)
    image = models.ImageField(upload_to=image_folder, blank=True, default=None)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})


class MoneyType(models.Model):
    name = models.CharField(max_length=10)
    exchangeRate = models.DecimalField(max_digits=4, decimal_places=2)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,)
    description = models.TextField(default='НАПИШИТЕ ОПИСАНИЕ ПРОДУКТА!', blank=True)
    # image = models.ImageField(upload_to=image_folder, blank=True, default=None)
    warranty = models.DecimalField(max_digits=2, decimal_places=0, default=0)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    money = models.ForeignKey(MoneyType, on_delete=models.CASCADE,)

    avaliable = models.BooleanField(default=True)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name

    def get_final_price(self):
        return int(self.price * self.money.exchangeRate)

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})





class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    item_total_price = models.DecimalField(max_digits=9, decimal_places=2, default=0)

    def __str__(self):
        return "Cart Item for product {0}".format(self.product.name)


class Cart(models.Model):
    items = models.ManyToManyField(CartItem, blank=True)
    cart_total_price = models.DecimalField(max_digits=9, decimal_places=2, default=0)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total_price=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()

    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()

    def change_quantity(self, quantity, item_id):
        cart_item = CartItem.objects.get(id=int(item_id))
        cart = self
        cart_item.quantity = int(quantity)
        cart_item.item_total_price = int(quantity) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.items.all():
            new_cart_total += float(item.item_total_price)
        cart.cart_total_price = new_cart_total
        cart.save()


ORDER_STATUS_CHOICES = (
    ('Принят в обработку', 'Принят в обработку'),
    ('Выполнен', 'Выполнен')
)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ForeignKey(Cart, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=225, blank=True)
    buying_type = models.CharField(max_length=40, choices=(('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')), default='Самовывоз')
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField(blank=True)
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])

    def __str__(self):
        return "Заказ № {0}".format(str(self.id))

    def detail(self):
        return "заказа № {0}".format(str(self.id))


def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.name), reversed=True))
        instance.slug = slug


pre_save.connect(pre_save_category_slug, sender=ParentCategory)
pre_save.connect(pre_save_category_slug, sender=Category)
pre_save.connect(pre_save_category_slug, sender=Product)

store/views.py
from django.shortcuts import render, reverse
from store.models import *
from django.http import HttpResponseRedirect, JsonResponse
from decimal import Decimal
from store.forms import OrderForm, RegistrationForm, LoginForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User


def main_view(request):
    parrentCategories = ParentCategory.objects.all()
    categories = Category.objects.all()
    login_my = LoginForm(request.POST or None)
    if login_my.is_valid():
        username = login_my.cleaned_data['username']
        password = login_my.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))

    register = RegistrationForm(request.POST or None)
    if register.is_valid():
        new_user = register.save(commit=False)
        username = login_my.cleaned_data['username']
        email = register.cleaned_data['email']
        password = register.cleaned_data['password']
        first_name = register.cleaned_data['first_name']
        last_name = register.cleaned_data['last_name']
        new_user.email = email
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session["cart_id"] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'parrentCategories': parrentCategories,
        'categories': categories,
        'cart': cart,
        'register': register,
        'login_my': login_my
    }
    return render(request, 'main.html', context)


def product_view(request, product_slug):
    parrentCategories = ParentCategory.objects.all()
    categories = Category.objects.all()
    login_my = LoginForm(request.POST or None)
    if login_my.is_valid():
        username = login_my.cleaned_data['username']
        password = login_my.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))

    register = RegistrationForm(request.POST or None)
    if register.is_valid():
        new_user = register.save(commit=False)
        username = login_my.cleaned_data['username']
        email = register.cleaned_data['email']
        password = register.cleaned_data['password']
        first_name = register.cleaned_data['first_name']
        last_name = register.cleaned_data['last_name']
        new_user.email = email
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session["cart_id"] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product = Product.objects.get(slug=product_slug)
    context = {
        'product': product,
        'parrentCategories': parrentCategories,
        'categories': categories,
        'cart': cart,
        'register': register,
        'login_my': login_my,
    }
    return render(request, 'product.html', context)


def category_view(request, category_slug):
    parrentCategories = ParentCategory.objects.all()
    categories = Category.objects.all()
    login_my = LoginForm(request.POST or None)
    if login_my.is_valid():
        username = login_my.cleaned_data['username']
        password = login_my.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))

    register = RegistrationForm(request.POST or None)
    if register.is_valid():
        new_user = register.save(commit=False)
        username = login_my.cleaned_data['username']
        email = register.cleaned_data['email']
        password = register.cleaned_data['password']
        first_name = register.cleaned_data['first_name']
        last_name = register.cleaned_data['last_name']
        new_user.email = email
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session["cart_id"] = cart_id
        cart = Cart.objects.get(id=cart_id)
    category = Category.objects.get(slug=category_slug)
    products_of_category = Product.objects.filter(category=category, avaliable=True)
    context = {
        'category': category,
        'products_of_category': products_of_category,
        'parrentCategories': parrentCategories,
        'categories': categories,
        'cart': cart,
        'register': register,
        'login_my': login_my,
    }
    return render(request, 'category.html', context)


def parent_category_view(request, parent_category_slug):
    parrentCategories = ParentCategory.objects.all()
    categories = Category.objects.all()
    login_my = LoginForm(request.POST or None)
    if login_my.is_valid():
        username = login_my.cleaned_data['username']
        password = login_my.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))

    register = RegistrationForm(request.POST or None)
    if register.is_valid():
        new_user = register.save(commit=False)
        username = login_my.cleaned_data['username']
        email = register.cleaned_data['email']
        password = register.cleaned_data['password']
        first_name = register.cleaned_data['first_name']
        last_name = register.cleaned_data['last_name']
        new_user.email = email
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session["cart_id"] = cart_id
        cart = Cart.objects.get(id=cart_id)
    try:
        parrentCategory = ParentCategory.objects.get(slug=parent_category_slug)
    except ParentCategory.DoesNotExist:
        parrentCategory = ParentCategory.objects.all()

    context = {
        'parrentCategories': parrentCategories,
        'categories': categories,
        'parrentCategory': parrentCategory,
        'cart': cart,
        'register': register,
        'login_my': login_my
    }
    return render(request, 'parrentCategory.html', context)


def cart_view(request):
    parrentCategories = ParentCategory.objects.all()
    categories = Category.objects.all()
    login_my = LoginForm(request.POST or None)
    if login_my.is_valid():
        username = login_my.cleaned_data['username']
        password = login_my.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))

    register = RegistrationForm(request.POST or None)
    if register.is_valid():
        new_user = register.save(commit=False)
        username = login_my.cleaned_data['username']
        email = register.cleaned_data['email']
        password = register.cleaned_data['password']
        first_name = register.cleaned_data['first_name']
        last_name = register.cleaned_data['last_name']
        new_user.email = email
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session["cart_id"] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context ={
        'parrentCategories': parrentCategories,
        'categories': categories,
        'cart': cart,
        'register': register,
        'login_my': login_my
    }
    return render(request, 'cart.html', context)

store/templates/account.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% endblock head %}

{% block content %}
    <article class="container-fluid">
        <div class="card">

            {% if order.count == 0 %}
                <h3>Ваша история заказов пуста.</h3>
            {% else %}
                {% if order_active.count == 0 %}
                    <h3>У вас нет активных заказов</h3>
                {% else %}
                    <h3>Активные заказы</h3>
                    <table class="table">
                        <tr>
                            <td style="width: 20%">Номер заказ</td>
                            <td style="width: 20%">Дата заказа</td>
                            <td style="width: 20%">Статус заказа</td>
                            <td style="width: 20%">Стоимость заказа</td>
                            <td style="width: 20%">Детали заказа</td>
                        </tr>
                        {% for item in order_active %}
                                <tr>
                                    <td>{{ item }}</td>
                                    <td>{{ item.date }}</td>
                                    <td>{{ item.status }}</td>
                                    <td>{{ item.total }}</td>
                                    <td><button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#exampleModal-{{ item.id }}">Детали {{ item.detail }}</button>
                                    </td>
                                </tr>
                        {% endfor %}
                    </table>
                {% endif %}
                {% if order_finished.count == 0 %}
                    <h3>У вас нет выполненых заказов</h3>
                {% else %}
                    <h3>Выполненые заказы</h3>
                    <table class="table">
                    <tr>
                        <td style="width: 20%">Номер заказ</td>
                        <td style="width: 20%">Дата заказа</td>
                        <td style="width: 20%">Статус заказа</td>
                        <td style="width: 20%">Стоимость заказа</td>
                        <td style="width: 20%">Детали заказа</td>
                    </tr>
                    {% for item in order_finished %}
                            <tr>
                                <td>{{ item }}</td>
                                <td>{{ item.date }}</td>
                                <td>{{ item.status }}</td>
                                <td>{{ item.total }}</td>
                                <td><button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#exampleModal-{{ item.id }}">Детали {{ item.detail }}</button>
                                </td>
                            </tr>
                    {% endfor %}
                {% endif %}

            </table>

            {% endif %}
        </div>
    </article>
    <!-- Modal -->
    {% for item in order_active %}
                <div class="modal fade" id="exampleModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-body">
                                <h5 class="modal-title text-center" id="exampleModalLabel">Детали {{ item.detail }}</h5>
                                <table class="table">
                                    <tr>
                                        <td>Товар</td>
                                        <td>К-во</td>
                                        <td>Цена</td>
                                    </tr>
                                    {% for order_item in item.items.items.all %}
                                            <tr>
                                                <td>{{ order_item.product.name }}</td>
                                                <td>{{ order_item.quantity }} шт.</td>
                                                <td>{{ order_item.item_total_price }} грв.</td>
                                            </tr>
                                    {% endfor %}
                                    <tr>
                                        <td colspan="2">Сумма:</td>
                                        <td>{{ item.total }} грв.</td>
                                    </tr>
                                </table>
                                <button type="button" class="btn btn-secondary btn-block" data-dismiss="modal">Закрыть</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
    {% for item in order_finished %}
                <div class="modal fade" id="exampleModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-body">
                                <h5 class="modal-title text-center" id="exampleModalLabel">Детали {{ item.detail }}</h5>
                                <table class="table">
                                    <tr>
                                        <td>Товар</td>
                                        <td>К-во</td>
                                        <td>Цена</td>
                                    </tr>
                                    {% for order_item in item.items.items.all %}
                                            <tr>
                                                <td>{{ order_item.product.name }}</td>
                                                <td>{{ order_item.quantity }} шт.</td>
                                                <td>{{ order_item.item_total_price }} грв.</td>
                                            </tr>
                                    {% endfor %}
                                    <tr>
                                        <td colspan="2">Сумма:</td>
                                        <td>{{ item.total }} грв.</td>
                                    </tr>
                                </table>
                                <button type="button" class="btn btn-secondary btn-block" data-dismiss="modal">Закрыть</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
{% endblock content %}
{% block scripts %}

{% endblock scripts %}

{% block styles %}

{% endblock styles %}

store/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% endblock head %}

{% block content %}
    <article class="container-fluid">


    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
          <li class="breadcrumb-item"><a href="{{ category.parentCategory.get_absolute_url }}">{{ category.parentCategory.name }}</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{ category.name }}</li>
      </ol>
    </nav>


        <div class="row">
            <div class="col-12">
                <div class="row">
                    {% for product in products_of_category %}
                    <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3 row-cart">
                            <div class="card w-100 card-menu" style="width: 18rem;">
                                <div class="card-header" onclick="location.href='{{ product.get_absolute_url }}'">
                                    <div class="card-img-container"><img src="{% static 'images/noImg.png' %}" alt="" class="card-img-top card-img"></div>
                                    <h5 class="text-center card-title">{{ product.name }}</h5>
                                </div>
                                <div class="card-body" onclick="location.href='{{ product.get_absolute_url }}'">
                                    <p class="card-text">{{ product.description }}</p>
                                    <p class="card-text">Цена: {{ product.get_final_price }} грв</p>
                                </div>
                                    {% if not request.user.is_authenticated %}
                                        <div class="btn-group btn-block">
                                            <button type="button" class="col-6 btn btn-primary" data-toggle="modal" data-target="#myModalLogin">Вход</button>
                                            <button type="button" class="col-6 btn btn-primary" data-toggle="modal" data-target="#myModalRegistration">Регистрация</button>
                                        </div>

                                    {% else %}
                                        <div class="btn-group btn-block">
                                            <button type="button" class="col-6 btn btn-primary add-to-cart" data-slug="{{ product.slug }}">В корзину</button>
                                            <button type="button" class="col-6 btn btn-primary" onclick="location.href='{{ product.get_absolute_url }}'">Детальнее</button>
                                        </div>
                                    {% endif %}
                            </div>


                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </article>
{% endblock content %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('.add-to-cart').on('click', function (e) {
                e.preventDefault();
                product_slug = $(this).attr('data-slug');
                data = {
                    product_slug: product_slug
                };
                $.ajax({
                    type: "GET",
                    url: '{% url "add_to_cart" %}',
                    data: data,
                    success: function (data) {
                        $("#cart_count").html(data.cart_total);
                    }
                })
            })
        })
    </script>
{% endblock scripts %}

{% block styles %}

{% endblock styles %}

store/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block content %}
    <article class="container-fluid">
        <div class="card">
                <div class="my-cart">
                    <h3 class="text-center">Ваш предварительный заказ</h3>
                    <div class="row">
                        <div class="col-6">
                            <table class="table table-striped">
                                    <tr>
                                        <td class="text-center">Товар</td>
                                        <td class="text-center">Количество</td>
                                        <td class="text-center">Цена</td>
                                        <td class="text-center"></td>
                                    </tr>
                                {% for item in cart.items.all %}
                                    <tr>
                                        <td class="text-center">{{ item.product.name }}</td>
                                        <td class="text-center">{{ item.quantity }}</td>
                                        <td class="text-center">{{ item.item_total_price }} грв.</td>
                                        <td></td>
                                    </tr>
                                {% endfor %}
                                    <tr>
                                        <td></td>
                                        <td class="text-center">Итого:</td>
                                        <td class="text-center">{{ cart.cart_total_price }} грв.</td>
                                        <td class="text-center"></td>
                                    </tr>
                            </table>
                        </div>
                        <div class="col-6">
                            <form action="{% url "make_order" %}" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-6">
                                        <div id="div_id_phone" class="form-group">
                                            <label for="id_phone" class="control-label  requiredField">Контактый телефон<span class="asteriskField">*</span></label>
                                            <div class="controls ">
                                                <input type="tel" name="phone" class="textinput textInput form-control" required="" id="id_phone" value="+380">
                                                <p id="hint_id_phone" class="help-block">Укажите котактный номер телефона.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-6">{{ form.buying_type|as_crispy_field }}</div>
                                </div>
                                <div class="row">
                                    <div class="col-12">{{ form.address|as_crispy_field }}</div>
                                    <div class="col-12">{{ form.comments|as_crispy_field }}</div>
                                </div>
                                <input type="submit" class="btn btn-success" value="Оформить заказ">
                            </form>
                        </div>
                    </div>

                </div>
        </div>
    </article>
{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function(){
            $('#div_id_address').hide();
            $('#id_buying_type').on('click', function () {
                buying_type = $(this).val();
                if (buying_type === 'delivery') {
                    $("#div_id_address").show();
                }
                if (buying_type === 'self') {
                    $("#div_id_address").hide();
                }
            })
        })
    </script>


{% endblock scripts %}

{% block styles %}

{% endblock styles %}